add_newline = true

format = """
$os\
$username\
$directory \
$time \
$git_branch\
$git_status\
\n$character\
"""

[os]
disabled = false
format = "[$symbol]($style) "
style = "bold green"

[os.symbols]
Android = ""

[username]
format = "as [ $user]($style) "

[directory]
truncation_length = 2
truncation_symbol = "../"
format = "in [ $path]($style)"
style = "bold blue"

[time]
disabled = false
use_12hr = true
time_format = "%R"
format = "at [ $time]($style)"

[git_status]
format = "[| $all_status/$ahead_behind |]($style)"
conflicted = "!="
ahead =  "==>"
behind = "<=="
diverged = "<=>"
up_to_date = "√"
untracked = "-?-"
stashed = "-S-"
modified = "-M-"
staged = "-!-"
renamed = "-R-"
deleted = "-D-"
typechanged = ""
