[[language]]
name = "c"
file-types = [ "c", "h" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "clang-format" }
language-servers = [ "clangd" ]

[[language]]
name = "cpp"
file-types = [ "cpp", "hpp" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "clang-format" }
language-servers = [ "clangd" ]

[[language]]
name = "java"
file-types = [ "java" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = [ "jdtls" ]
