use-grammars = {only = ["c", "cpp", "lua", "toml", "markdown"]}

[[language]]
name = "c"
file-types = [ "c", "h" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "clang-format" }
language-servers = [ "clangd" ]

[[language]]
name = "cpp"
file-types = [ "cpp", "hpp" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "clang-format" }
language-servers = [ "clangd" ]

[[language]]
name = "lua"
file-types = ["lua"]
auto-format = true
indent = {tab-width = 2, unit = "  "}
formatter = {command = "stylua", args = ["-"]}
language-servers = ["lua-language-server"]
